### ISSUE TITLE
Fresh docker compose install not functional

### ISSUE THREAD

**Issue by Glynax** [CyferShepard/Jellystat#175]
**Describe the bug**
Alright I've been trying to figure this out for a few days now, I've started fresh a few times and I can't get jellystat to consistently work.
I have a pretty standard jellyfin docker compose set up I think, with the base url of /jellyfin behind a NGINX subfolder reverse proxy. Jellyfin is using host networking mode in docker and so is jellystat

**Environment Details (please complete the following information):**
 - OS: [Ubuntu desktop]
 - Browser [Opera]
 - Jellystat Version [1.0.9]
 - Jellyfin Version [10.8.13]

**To Reproduce**
All I have to do is delete the DB and start fresh and make a user for jellystat, connect to the server which it seems to accept and then the libraries never show up.

**Expected behavior**
I'm honestly not sure what I'm doing wrong. I have quite a few libraries and varied ones, maybe it doesn't like some of them?

**Screenshots**
![image](https://github.com/CyferShepard/Jellystat/assets/7043861/6dc37883-5f03-4c4d-873c-ef2387d98a91)
![image](https://github.com/CyferShepard/Jellystat/assets/7043861/680c4331-66a5-4536-b045-7583e56a1eb9)

**Task Logs**
If applicable, add Task Logs for your problem.

**Container Logs**
If applicable, add Container Logs for your problem.
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }

**Additional context**
version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    network_mode: host
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ******
    volumes:
    - /opt/jellystat/postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ******
      POSTGRES_IP: 192.168.1.134
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    network_mode: host
    ports:
      - "3000:3000" #Server Port
    volumes:
      - /opt/jellystat/backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
    restart: unless-stopped

**Comment by CyferShepard** [comment]
Hey @Glynax , can you try using the `unstable` tag? There was a bug which was a fix was deployed for on unstable

**Comment by Glynax** [comment]
Same exact error on unstable

**Comment by Glynax** [comment]
I've tried starting fresh again on latest and here are all the logs, maybe something in here? 
It also fails immediately when trying to sync with jellyfin
```
jellystat-jellystat-db-1  | The files belonging to this database system will be owned by user "postgres".
jellystat-jellystat-db-1  | This user must also own the server process.
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | The database cluster will be initialized with locale "en_US.utf8".
jellystat-jellystat-db-1  | The default database encoding has accordingly been set to "UTF8".
jellystat-jellystat-db-1  | The default text search configuration will be set to "english".
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | Data page checksums are disabled.
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
jellystat-jellystat-db-1  | creating subdirectories ... 
jellystat-jellystat-db-1  | ok
jellystat-jellystat-db-1  | selecting dynamic shared memory implementation ... posix
jellystat-jellystat-db-1  | selecting default max_connections ... 
jellystat-jellystat-db-1  | 100
jellystat-jellystat-db-1  | selecting default shared_buffers ... 
jellystat-jellystat-db-1  | 128MB
jellystat-jellystat-db-1  | selecting default time zone ... 
jellystat-jellystat-db-1  | Etc/UTC
jellystat-jellystat-db-1  | creating configuration files ... 
jellystat-jellystat-db-1  | ok
jellystat-jellystat-db-1  | running bootstrap script ... 
jellystat-jellystat-db-1  | ok
jellystat-jellystat-db-1  | performing post-bootstrap initialization ... 
jellystat-jellystat-db-1  | ok
jellystat-jellystat-db-1  | syncing data to disk ... 
jellystat-jellystat-db-1  | ok
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | Success. You can now start the database server using:
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | initdb: warning: enabling "trust" authentication for local connections
jellystat-jellystat-db-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
jellystat-jellystat-db-1  | waiting for server to start....
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.406 UTC [49] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.407 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.410 UTC [52] LOG:  database system was shut down at 2024-03-05 03:46:52 UTC
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.412 UTC [49] LOG:  database system is ready to accept connections
jellystat-jellystat-db-1  |  done
jellystat-jellystat-db-1  | server started
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | waiting for server to shut down....2024-03-05 03:46:52.518 UTC [49] LOG:  received fast shutdown request
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.518 UTC [49] LOG:  aborting any active transactions
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.519 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.520 UTC [50] LOG:  shutting down
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.520 UTC [50] LOG:  checkpoint starting: shutdown immediate
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.524 UTC [50] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.005 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/14EAA70, redo lsn=0/14EAA70
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.526 UTC [49] LOG:  database system is shut down
jellystat-jellystat-1     | 
jellystat-jellystat-1     | > jfstat@1.0.9 start
jellystat-jellystat-1     | > cd backend && node server.js
jellystat-jellystat-1     | 
jellystat-jellystat-1     | 
jellystat-jellystat-db-1  |  done
jellystat-jellystat-db-1  | server stopped
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | PostgreSQL init process complete; ready for start up.
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.629 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.629 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.629 UTC [1] LOG:  listening on IPv6 address "::", port 5432
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.630 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.632 UTC [63] LOG:  database system was shut down at 2024-03-05 03:46:52 UTC
jellystat-jellystat-db-1  | 2024-03-05 03:46:52.635 UTC [1] LOG:  database system is ready to accept connections
jellystat-jellystat-1     | [JELLYSTAT] Database created
jellystat-jellystat-1     | FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
jellystat-jellystat-1     | FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
jellystat-jellystat-1     | [JELLYSTAT] Server listening on http://127.0.0.1:3000
jellystat-jellystat-1     | Activity Interval: 1000
jellystat-jellystat-1     | JsonWebTokenError: invalid signature
jellystat-jellystat-1     |     at /app/node_modules/jsonwebtoken/verify.js:171:19
jellystat-jellystat-1     |     at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
jellystat-jellystat-1     |     at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
jellystat-jellystat-1     |     at authenticate (/app/backend/server.js:111:27)
jellystat-jellystat-1     |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
jellystat-jellystat-1     |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
jellystat-jellystat-1     |     at /app/node_modules/express/lib/router/index.js:286:9
jellystat-jellystat-1     |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
jellystat-jellystat-1     |     at next (/app/node_modules/express/lib/router/index.js:280:10)
jellystat-jellystat-1     |     at compression (/app/node_modules/compression/index.js:220:5)
jellystat-jellystat-1     | JsonWebTokenError: invalid signature
jellystat-jellystat-1     |     at /app/node_modules/jsonwebtoken/verify.js:171:19
jellystat-jellystat-1     |     at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
jellystat-jellystat-1     |     at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
jellystat-jellystat-1     |     at authenticate (/app/backend/server.js:111:27)
jellystat-jellystat-1     |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
jellystat-jellystat-1     |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
jellystat-jellystat-1     |     at /app/node_modules/express/lib/router/index.js:286:9
jellystat-jellystat-1     |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
jellystat-jellystat-1     |     at next (/app/node_modules/express/lib/router/index.js:280:10)
jellystat-jellystat-1     |     at compression (/app/node_modules/compression/index.js:220:5)
jellystat-jellystat-1     | JsonWebTokenError: invalid signature
jellystat-jellystat-1     |     at /app/node_modules/jsonwebtoken/verify.js:171:19
jellystat-jellystat-1     |     at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
jellystat-jellystat-1     |     at module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
jellystat-jellystat-1     |     at authenticate (/app/backend/server.js:111:27)
jellystat-jellystat-1     |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
jellystat-jellystat-1     |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
jellystat-jellystat-1     |     at /app/node_modules/express/lib/router/index.js:286:9
jellystat-jellystat-1     |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
jellystat-jellystat-1     |     at next (/app/node_modules/express/lib/router/index.js:280:10)
jellystat-jellystat-1     |     at compression (/app/node_modules/compression/index.js:220:5)
jellystat-jellystat-1     | INSERT INTO app_config ("APP_USER","APP_PASSWORD") VALUES ($1,$2)
jellystat-jellystat-1     | { isValid: true, errorMessage: '' }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:84:22',
jellystat-jellystat-1     |   Message: 'users.filter is not a function'
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at JellyfinAPI.getLibraries (/app/backend/classes/jellyfin-api.js:224:49',
jellystat-jellystat-1     |   Message: "Cannot read properties of undefined (reading 'filter')"
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at JellyfinAPI.getLibraries (/app/backend/classes/jellyfin-api.js:224:49',
jellystat-jellystat-1     |   Message: "Cannot read properties of undefined (reading 'filter')"
jellystat-jellystat-1     | }
jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at JellyfinAPI.getLibraries (/app/backend/classes/jellyfin-api.js:224:49',
jellystat-jellystat-1     |   Message: "Cannot read properties of undefined (reading 'filter')"
jellystat-jellystat-1     | }
```

**Comment by nickvk** [comment]
I have the exact same issue. Fresh installation and also no results from the library. I only get the error "Error: No Libararies found to sync.". Can this please be fixed?

**Comment by CyferShepard** [comment]
Hey @nickvk , can you try using the unstable tag and see if there are any changes, im constantly going over the code and fixing areas that may look like they could be issues. Unfortunately im not experiencing this issue myself so i wont know if its fixed until i get feedback. I haven't mentioned it yet because im not confident there has been a change that fixes the issue. But if you notice any different errors in the docker logs this may help.

**Comment by nickvk** [comment]
Hi, great. Thanks guys! Going to the unstable tag fixed it.

Totally unrelated, but maybe you guys can help me with this: I am running the nightly version of Jellyfin. Is there some way to install the "Playback Reporting" plugin? I would like this data to be in Jellystat aswell. But I can't seem to install this plugin. I tried going to another tag for Jellyfin (latest) but that breaks my Jellyfin installation.

Hope you can help me with this aswell. Thanks in advance!

**Comment by Glynax** [comment]
> I'm not sure it's a hugely helpful point, but just in case: I can run the container without problem if I use the docker compose example that's on docker hub. However, just changing the jellystat-db container from 'postgres:15.2' to 'postgres' seems to break it. I'm back to 15.2, since everything works fine there.

Just wanted to tack on that unstable didn't fix it for me by itself, I had to specify the postgresDB version and start fresh again but we're up and running now thank you so much!

**Comment by tomoffel85** [comment]
hey, 
running into the same error even with the unstable tag, it still tells me "Error: No Libararies found to sync."

hope someone can help :)

Thank you!

**Comment by CyferShepard** [comment]
hey @tomoffel85 , can you check in issue #163 , can you also provide docker logs so i can check this out? Some people reported adding http:// to the front of their jellyfin ip helps

**Comment by tomoffel85** [comment]
> hey @tomoffel85 , can you check in issue #163 , can you also provide docker logs so i can check this out? Some people reported adding http:// to the front of their jellyfin ip helps

Yeah! Thank you got it fixed with the "http://" infront of my Jellyfin IP :)

great support!

**Comment by Glynax** [comment]
I have moved jellyfin and jellystat to another box, and I figured I'd try starting jellystat fresh to see if it cleared up any of the issues I've been having (issues already open here). No dice now I'm back to this with it never succeeding with syncing or importing or doing anything with the server even though it accepts the url and api key. Running on unstable, 1.1.0



`
> jfstat@1.1.0 start
> cd backend && node server.js

[JELLYSTAT] Database created
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000
http://192.168.1.148:8096 true
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:112:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:112:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: '/app/backend/classes/jellyfin-api.js:321:21'
    },
    {
      TraceIndex: 4,
      line: 'at async /app/backend/routes/proxy.js:158:27'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getRecentlyAdded (/app/backend/classes/jellyfin-api.js:321:48',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:321:48'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:158:27'
    }
  ],
  Message: "Cannot read properties of undefined (reading 'Id')",
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:112:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:112:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:146:23'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:112:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:112:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:146:23'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:112:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:112:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:146:23'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}`

`The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-05-08 00:25:11.467 UTC [48] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-05-08 00:25:11.468 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-05-08 00:25:11.471 UTC [51] LOG:  database system was shut down at 2024-05-08 00:25:11 UTC
2024-05-08 00:25:11.473 UTC [48] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2024-05-08 00:25:11.589 UTC [48] LOG:  received fast shutdown request
2024-05-08 00:25:11.590 UTC [48] LOG:  aborting any active transactions
2024-05-08 00:25:11.591 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2024-05-08 00:25:11.591 UTC [49] LOG:  shutting down
2024-05-08 00:25:11.592 UTC [49] LOG:  checkpoint starting: shutdown immediate
2024-05-08 00:25:11.596 UTC [49] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.005 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
2024-05-08 00:25:11.598 UTC [48] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2024-05-08 00:25:11.702 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2024-05-08 00:25:11.702 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-05-08 00:25:11.702 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-05-08 00:25:11.703 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-05-08 00:25:11.706 UTC [62] LOG:  database system was shut down at 2024-05-08 00:25:11 UTC
2024-05-08 00:25:11.708 UTC [1] LOG:  database system is ready to accept connections
2024-05-08 00:30:11.806 UTC [60] LOG:  checkpoint starting: time`

**Comment by CyferShepard** [comment]
Hey @Glynax , can you provide the URL you entered aswell as the compose file you used when redeploying?

**Comment by Glynax** [comment]
Sorry I knew I forgot something.

http://192.168.1.148:8096 this is also the same box jellystat is running from as well

`version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filler
    volumes:
    - /opt/jellystat/postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:unstable
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: filler
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'filler'
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - /opt/jellystat/backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
    restart: unless-stopped
networks:
  default:
`

**Comment by Glynax** [comment]
Just wanted to say I'm still having issues, I tried a clean slate and deleted everything with this update. This is what I get currently, all tasks fail. And of course nothing ever works because it never really sees the server even though it seems to accept it on initial startup with http://192.168.1.120:8096 
This is on a new box if you're wondering about the IP change.
![image](https://github.com/CyferShepard/Jellystat/assets/7043861/2dc1a5a4-1a12-42f1-b3ab-1cbd6c405f16)
![image](https://github.com/CyferShepard/Jellystat/assets/7043861/88c9e9ac-4cb2-4ab4-acc2-e0be342a5186)


`> jfstat@1.1.0 start
> cd backend && node server.js

Error: connect ECONNREFUSED 172.19.0.2:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: connect ECONNREFUSED 172.19.0.2:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.19.0.2',
  port: 5432
}

Node.js v22.2.0
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice

> jfstat@1.1.0 start
> cd backend && node server.js

[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000
http://192.168.1.120 true
[JELLYFIN-API] {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/node_modules/axios/dist/node/axios.cjs:837:14'
    },
    {
      TraceIndex: 2,
      line: '/app/node_modules/axios/dist/node/axios.cjs:3087:25'
    },
    { TraceIndex: 3, line: 'node:events:520:28' },
    {
      TraceIndex: 4,
      line: '/app/node_modules/follow-redirects/index.js:38:24'
    },
    { TraceIndex: 5, line: 'node:events:520:28' },
    { TraceIndex: 6, line: 'node:_http_client:502:9' },
    { TraceIndex: 7, line: 'node:events:520:28' },
    { TraceIndex: 8, line: 'node:internal/streams/destroy:170:8' },
    { TraceIndex: 9, line: 'node:internal/streams/destroy:129:3' },
    { TraceIndex: 10, line: 'node:internal/process/task_queues:82:21' },
    {
      TraceIndex: 11,
      line: '/app/node_modules/axios/dist/node/axios.cjs:3877:41'
    },
    { TraceIndex: 12, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 13,
      line: '/app/backend/classes/jellyfin-api.js:420:24'
    },
    {
      TraceIndex: 14,
      line: 'at async /app/backend/routes/proxy.js:205:22'
    }
  ],
  Message: 'connect ECONNREFUSED 192.168.1.120:80',
  url: undefined
}
http://192.168.1.120:8096 true
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:112:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:112:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/proxy.js:146:23'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}`

**Comment by CyferShepard** [comment]
This looks like a network issue as I see it fails to connect to the db at the top, which is strange since it shouldn't proceed from there. Can you confirm if both jellystat and jellystat-db are on the same docker-network?

**Comment by Glynax** [comment]
It's on the same box in the same docker compose which you can see up a comment or two. I've even tried making both of them host networking just so I can explicitly use the IP of that machine and it's the same exact thing where jellystat loads but nothing actually works

**Comment by danisalgueiro** [comment]
Hi, same problem here. Suddenly, without updating anything, it stopped working. Same docker, network, container and can't connect to postgreSQL database.

The log file, in case it can help, says:

jellystat  | Node.js v21.5.0
jellystat  | 
jellystat  | > jfstat@1.0.9 start
jellystat  | > cd backend && node server.js
jellystat  | 
jellystat  | [JELLYSTAT] Database exists. Skipping creation
jellystat  | Error: connect ECONNREFUSED 172.18.0.6:5432
jellystat  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
jellystat  | FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
jellystat  | FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
jellystat  | node:internal/process/promises:289
jellystat  |             triggerUncaughtException(err, true /* fromPromise */);
jellystat  |             ^
jellystat  | 
jellystat  | Error: connect ECONNREFUSED 172.18.0.6:5432
jellystat  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
jellystat  |   errno: -111,
jellystat  |   code: 'ECONNREFUSED',
jellystat  |   syscall: 'connect',
jellystat  |   address: '172.18.0.6',
jellystat  |   port: 5432
jellystat  | }
jellystat  | 
jellystat  | Node.js v21.5.0

**Comment by CyferShepard** [comment]
hey @danisalgueiro , can you try stopping both the db and jellystat, start the db first, then jellystat?

**Comment by danisalgueiro** [comment]
Thanks for the reply. Tried, but still giving the same error. I'm going to try to check the database logs in case it gives any additional clues.

**Comment by CyferShepard** [comment]
Yea this seems like a database issue, the logs are saying it cant connect to it, check to ensure both containers are on the same docker network, and that there are no errors in the db logs

**Comment by patcfly** [comment]
I am also experiencing this issue. Anyone have a fix? I have jellyseer working fine w/ jellyfin.

The container van def connect to jellyfin, 

[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getAdmins (/app/backend/classes/jellyfin-api.js:118:21',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:118:21'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: '/app/backend/classes/jellyfin-api.js:327:21'
    },
    {
      TraceIndex: 4,
      line: 'at async /app/backend/routes/api.js:133:38'
    }
  ],
  Message: 'users?.filter is not a function',
  url: undefined
}
[JELLYFIN-API] {
  ErrorAt: 'at JellyfinAPI.getRecentlyAdded (/app/backend/classes/jellyfin-api.js:327:48',
  ErrorLines: [
    {
      TraceIndex: 1,
      line: '/app/backend/classes/jellyfin-api.js:327:48'
    },
    { TraceIndex: 2, line: 'node:internal/process/task_queues:95:5' },
    {
      TraceIndex: 3,
      line: 'at async /app/backend/routes/api.js:133:38'
    }
  ],
  Message: "Cannot read properties of undefined (reading 'Id')",
  url: undefined
}

**Comment by Manu343726** [comment]
Just my two cents here:

Initially hit this issue by pulling the image with the latest tag I saw on github (1.1.2). After reading here I changed to "latest" as documented in the dockerhub docker compose example and everything is synching correctly now. Both were with Postgres 15.2. I did no settings changes between the 2 jellystat images.

Hope it helps.
