### ISSUE TITLE
JellyStat doesn't add all items to its library

### ISSUE THREAD

**Issue by Traace** [CyferShepard/Jellystat#34]
Hi,
using latest docker image on debian 11 host. 

JellyStat doesn't add all library items to its database. Did 5 syncs already, the logs show the status success for all of them, too.

```
Movies
JellyStat Count: 114
Jellyfin Count: 1345
JellyStat Size: 33 GB
True Size: About 5 TB

Music
JellyStat Count: 199
Jellyfin Count: 3349
JellyStat Size: 0 KB
True Size: About 400GB
```
For Music it also says type is: Movies. I double checked the library in jellyfin, it is detected as a Music library there.

**Comment by CyferShepard** [comment]
Hi @Traace , can you show the logs for the sync task?

**Comment by Traace** [comment]
Sure

First Sync after a clean installation:
```
Syncing... 1/3
Beginning Library Item Sync
575 Rows Inserted. 0 Rows Updated.
0 Library Items Removed.
Item Sync Complete
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 1521 Rows Inserted. 0 Rows Updated.
0 Seasons Removed.
Episodes: 20399 Rows Inserted. 0 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
27 Item Info inserted.
0 Item Info Removed.
20399 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete
```

A manual sync after first sync completed with success:
```
Syncing... 1/3
Beginning Library Item Sync
0 Rows Inserted. 575 Rows Updated.
0 Library Items Removed.
Item Sync Complete
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 1521 Rows Updated.
0 Seasons Removed.
Episodes: 3 Rows Inserted. 20396 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
0 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete
```

**Comment by CyferShepard** [comment]
This seems to be an issue with the Item Information as i can see its adding 575 library items in the first one but only 27 of the corresponding information. Il do some digging on my side but my best guess at the moment is its timing out due to such large volumes of requests to the Jellyfin API

**Comment by Traace** [comment]
I don't think it is due to a timeout because JellyStat was able to sync over 19k series files with a total size of 6.6 TB just fine.

**Comment by CyferShepard** [comment]
Can you grab the latest version and let me know if the problem still exists? There was a bug which has been addressed, I haven't looked into your issue yet due to that one but maybe it's the same issue as it both dealth with the sync code

**Comment by Traace** [comment]
Unfortunately the new Update didn't fix it.

```
Syncing... 1/3
Beginning Library Item Sync
0 Rows Inserted. 575 Rows Updated.
0 Library Items Removed.
Item Sync Complete
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 1520 Rows Updated.
0 Seasons Removed.
Episodes: 3 Rows Inserted. 20396 Rows Updated.
0 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
0 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete
```

**Comment by CyferShepard** [comment]
Hi @Traace , do you mind sending me a screenshot of your library folders and their types? it can be found in Jellyfins Dashboard.

**Comment by NeuroDawg** [comment]
Hey @CyferShepard,

I have the same problem. My movies folders are being undercounted. You have a screenshot of my library files in our other discussion (thanks for that quick fix, btw!).

Here is a screenshot of Jellystat showing my library info:
![image](https://github.com/CyferShepard/Jellystat/assets/59210675/1b3d0543-2886-4e79-9732-35c44351a565)

And here is my log file (most recent sync, I don't have the original log from yesterday as there are too many recent automatic sync logs):

```
Syncing... 1/3
Beginning Library Item Sync
0 Rows Inserted. 169 Rows Updated.
0 Library Items Removed.
Item Sync Complete
Syncing... 2/3
Beginning Seasons and Episode sync
Seasons: 0 Rows Inserted. 321 Rows Updated.
0 Seasons Removed.
Episodes: -5 Rows Inserted. 3981 Rows Updated.
7 Episodes Removed.
Sync Complete
Syncing... 3/4
Beginning File Info Sync
0 Item Info inserted.
0 Item Info Removed.
2 Episodes Info inserted.
0 Episodes Info Removed.
Info Sync Complete
Syncing... 4/4
Removing Orphaned FileInfo/Episode/Season Records
Orphaned FileInfo/Episode/Season Removed.
Sync Complete
```

**Comment by CyferShepard** [comment]
Hi @NeuroDawg , by any chance are you using the Merge-Versions Plugin?

**Comment by NeuroDawg** [comment]
@CyferShepard - I am not. Here's a photo of all the plugins I'm using:
![image](https://github.com/CyferShepard/Jellystat/assets/59210675/a011542b-2e41-4347-8d18-896f7330e8a4)

**Comment by CyferShepard** [comment]
Hi @NeuroDawg , can you pull the latest version navigate to this url? http://jellystat_ip:jellystat_port/debugger/data.

Since its very hard to do debugging like this, i added a page to show me data in the db vs data from the api and a file with the data that doesnt get imported.

**Comment by NeuroDawg** [comment]
Here are the files:

[MissingItemData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645798/MissingItemData.json.txt)
[MissingLibraryData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645800/MissingLibraryData.json.txt)
[MissingEpisodeData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645801/MissingEpisodeData.json.txt)

Here's a screenshot of the debug page (I don't understand the counts shown, they don't make much sense to me and what I have in my libraries):
![image](https://github.com/CyferShepard/Jellystat/assets/59210675/5d8f6aac-56ba-4e21-b849-ed6559d09ddb)

Let me know if there's any thing else I can do to help with debugging. I'm happy to send log files if needed.

**Comment by NeuroDawg** [comment]
Out of curiosity, did you start coding this from scratch, or did you start with [embystat](https://github.com/mregni/EmbyStat)? I've been running embystat for a while now, and while it doesn't track users' activity worth a damn, it does an accurate job of pulling numbers from my server, and can even tell me when a TV series is incomplete. I'm not a coder, but it seems it may be worthwhile to look at that project and how it pulls data via the API. 

Anyway, just a suggestion. I appreciate your efforts and think your project is going to be great for the Jellyfin community.

**Comment by CyferShepard** [comment]
Thanks for the files, hopefully this helps. Tbh I never looked into how any of the alternate softwares worked. I coded this from scratch with an idea of how I wanted it to work. Il look into embystats code to see how it does it's sync, I never got it to work when I tried a while back so the thought never crossed my mind.

**Comment by FaNt4zMa** [comment]
Same issue here. **My Shows are counted correctly but my Movies and Music libraries aren't.** The debugger shows no difference in API count vs DB count. I do believe it runs into some issues because of how many files there is. I have over 5011 songs and 452 movies. Also I would like if the Playlist library wasn't counted as a one, it is automatically created by Jellyfin and is not a library I actually use. Music library type is also mislabeled (Movies instead of Songs)

Here's [some screenshot](https://imgur.com/a/LSr10fD) for context, I'm running the last image and I even tried with a fresh db. Let me know If I can help.

**Comment by CyferShepard** [comment]
Hi @FaNt4zMa , can you get the latest image, the debugger should be abit more granular, can you also provide me with the Raw data from the new options, il analyze it on my side

**Comment by CyferShepard** [comment]
> Here are the files:
> 
> [MissingItemData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645798/MissingItemData.json.txt) [MissingLibraryData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645800/MissingLibraryData.json.txt) [MissingEpisodeData.json.txt](https://github.com/CyferShepard/Jellystat/files/11645801/MissingEpisodeData.json.txt)
> 
> Here's a screenshot of the debug page (I don't understand the counts shown, they don't make much sense to me and what I have in my libraries): ![image](https://user-images.githubusercontent.com/59210675/243182197-5d8f6aac-56ba-4e21-b849-ed6559d09ddb.png)
> 
> Let me know if there's any thing else I can do to help with debugging. I'm happy to send log files if needed.

Hi @NeuroDawg , can you pull the latest image and navigate back to that page, Iv split the data to make more sense plus added options to dump the raw data

**Comment by FaNt4zMa** [comment]
Somehow the debugger still reports no difference..? Here's [screenshot](https://imgur.com/a/MASIkmV) of my libraries (I hope thats you're asking) and my debugger data.
[RawSeasonData.json.txt](https://github.com/CyferShepard/Jellystat/files/11653729/RawSeasonData.json.txt)
[RawItemData.json.txt](https://github.com/CyferShepard/Jellystat/files/11653730/RawItemData.json.txt)
[RawLibData.json.txt](https://github.com/CyferShepard/Jellystat/files/11653732/RawLibData.json.txt)
[RawEpisodeData.json.txt](https://github.com/CyferShepard/Jellystat/files/11653733/RawEpisodeData.json.txt)

**Comment by CyferShepard** [comment]
Hi @FaNt4zMa , i managed to isolate the issue where it synced you playlist, that should now remove itself when you pull the latest version and re-sync. I also fixed the label for music. In regards to your sync count being incorrect, can you tell me which library is out of sync or is it all of them. I think it may be an issue with jellyfins api. Found a similar issue with someone elses library where the sync pulled absolutely nothing because of this. Will be looking into that and hopefully the jellyfin team can assist.

**Comment by FaNt4zMa** [comment]
The Movies count and Songs count are wrong, only my TV Shows are counted correctly. I'm currently at work so I can't pull the latest image yet, will report tonight after I do.

**Comment by FaNt4zMa** [comment]
I have pulled the latest image and on the first sync it "failed" (it only removed the playlist library data) then on second sync it succed to remove my playlist library so thanks! 

[One other typo](https://imgur.com/a/C45d7dl) you might have missed tho.. :)

**Comment by CyferShepard** [comment]
Hi everyone, just an update, this issue is now confirmed to be because of Jellyfins API. It does not return everything within the libraries. Will update when i get some assistance from jellyfins team

**Comment by CyferShepard** [comment]
Hi everyone, a fix has been pushed with version 1.0.4.8. Let me know if it helps

**Comment by NeuroDawg** [comment]
> Hi everyone, a fix has been pushed with version 1.0.4.8. Let me know if it helps
Yep. That fixed it for me. Thank you very much!

**Comment by CyferShepard** [comment]
No problem @NeuroDawg, been one confusing bug, glad its sorted. @Traace is it fixed for you aswell?

**Comment by FaNt4zMa** [comment]
It fixed it for me! Thank you so much for you hard work 😄 And the final typo is the Music library is gone aswell!

**Comment by CyferShepard** [comment]
This issue has been fixed

**Comment by FaNt4zMa** [comment]
Found this weird new bug with the counting. Deleted episodes (I would assume music/movies too) do not get removed from the count, even tho [the logs shows it should be](https://imgur.com/a/1HKxA5u)...?

**Comment by CyferShepard** [comment]
Hmm, thats weird, i can see its being removed. Im reworking the sync process abit in the new version and also added some redundant cleanup, hopefully this will fix it, once the new version is out of unstable and on the main let me know if you have the same issue, then we can reopen this bug. PS this change is not yet on the unstable branch

**Comment by FaNt4zMa** [comment]
Seems like its still an issue? Also the Total Files count and Episodes count don't match for some reason. Here's [screenshots](https://imgur.com/a/7PPLFBh)

**Comment by CyferShepard** [comment]
Hey @FaNt4zMa , are you using the latest image? also can you let me know if you removed any media recently?

**Comment by CyferShepard** [comment]
Okay I'm digging into the issue now, it doesn't seem to be a sync issue but a stat issue. I'm just double checking how the data is being tallied but can confirm so far from what I see that sync is working, just that the totals don't line up.

**Comment by FaNt4zMa** [comment]
No, like you said, the totals don't line up. I have 1409 episodes on my Jellyfin and Jellystat is reporting 1454. In the sync logs, it looks like those 45 extra episodes are getting removed.

I am using the latest version and haven't deleted media recently

**Comment by CyferShepard** [comment]
This is strange but i can replicate it on my instance aswell, will post an update once i can figure this out

**Comment by CyferShepard** [comment]
Ah, i see the issue, so in the latest image, i introduced a feature where data is no longer deleted but rather its archived, IE theres a flag thats set on the library/items as archived whenever its no longer available on by jellyfin. I just forgot to add this flag in the query that does the episode/show count. Once i did that my item count now matched what jellyfin was showing me. Let me add this quickly and will send a message when the image is updated

**Comment by CyferShepard** [comment]
Okay get the latest unstable version and try now

**Comment by FaNt4zMa** [comment]
No change for me, count is still off. I can see from the logs that they're being archived and the library stats getting updated. 

Should I start from a clean DB at that point? Maybe it would help lol. Seems like my backups havent been working since June. Backup task doesn't work so I'll have to start from scratch but If it can avoid you making unnecessary changes because of a single weird case..?

**Comment by CyferShepard** [comment]
hmm, thats weird, maybe check your backup path in docker and see where's it being stored. Also there's no need to start fresh, the data is correct its just an issue with how the data is being counted. Il double check if i missed anything on my side

**Comment by CyferShepard** [comment]
Hey @FaNt4zMa , can you pull the latest ```unstable``` image and try a full sync and let me know if the results are any better

**Comment by FaNt4zMa** [comment]
Still no change, but while the [Episode Info Sync](https://imgur.com/a/RwqTsHs) was happening, the container console had output [this](https://imgur.com/a/bWJ2sCu)..? Its able to sync the other stuff no problem

**Comment by CyferShepard** [comment]
Huh, i think i know whats going on there, Basically the archived flag is meant to flow downstream, ie if a show is archived, then archive the seasons, then the episodes. But im assuming when you updated to the image that has this code change for the archiving, it deleted the show in the old build but left the seasons and episodes alone as false. With this logic it wont get marked as archived as the main parent show doesn't exist. 

A quick and dirty fix on your side would be to backup the data, download it, then open it in something like Notepad++ or VS Code, do a search and replace for ```"archived":false``` and replace it with ```"archived":true```. Then just redo a full sync and everything should reflect correctly.

**Comment by FaNt4zMa** [comment]
Sadly the backup won't work for me.. I can see its trying to create a backup from the Modified date of the folder but it doesnt actually create anything. The logs shows the backup as sucessful. Could it be because its on my C: drive root folder and docker/the container doesn't have permissions? I never had this issue with anything before

**Comment by FaNt4zMa** [comment]
@CyferShepard I did the whole process, replaced every instances of "archived":false by "archived":true, restored the backup, and the result is the same. No changes

**Comment by CyferShepard** [comment]
this is strange, do you mind sending me an updated screenshot of your library count vs what's getting pulled in the logs, I'm need to investigate further

**Comment by CyferShepard** [comment]
You wiped the database first and then restored right? Just had to check

**Comment by CyferShepard** [comment]
Il look into expanding the granularity of the backups, there is a possibility of restoring only your activity but thats gonna require some splicing of the backup file. Let me see if i can write you a quick script and send it later to basically split your backup into each dataset so youl be able to only restore the activity

**Comment by CyferShepard** [comment]
heres a quick and dirty app to split the backup, let me know if theres any issues (probably will be). https://jellystatbackupsplitter.netlify.app/
